### ISSUE TITLE
Rename (either) of `Tracer` types.

### ISSUE THREAD

**Issue by phadej** [avieth/contra-tracer#1]
![Screenshot from 2021-05-29 12-58-13](https://user-images.githubusercontent.com/51087/120066113-9c42ca80-c07d-11eb-9bfe-3b8a1f51216e.png)

haddocks are confusing. That screenshot is from `Control.Tracer` module haddocks, yet e.g. that `emit` returns `Control.Tracer.Arrow.Tracer` which is confusing to uninitiated. Type of `arrow` is a puzzle too.

EDIT: yes, kinds / amount of type variables can help disambiguate, but why make it so subtle?

**Comment by phadej** [comment]
ping @avieth

**Comment by avieth** [comment]
Agree 100%. Any suggestions for a different name? `TracerArrow` perhaps?

**Comment by phadej** [comment]
No preferences, `ArrTracer`, `TracerArrow`, `TraceA`, `TracerArrow`, all are fine.

**Comment by phadej** [comment]
Looks like this is fixed and released. Thanks!
